# Server Configuration (Default to 8081 as 8080 is occupied by Oracle TNS listener service on this machine)
server.port=8081

# Application Name
spring.application.name=resume-analyzer-backend

# Isolated Development Database (Isolated test database in target directory)
spring.datasource.url=jdbc:sqlite:target/dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
